### ISSUE TITLE
Time until departure as hours and minutes

### ISSUE THREAD

**Issue by njustus** [custom-cards/rmv-card#9]
Currently, the time until departure is displayed as minutes only. This works really good for departures in the near future, but it’s a little cumbersome for departures later that day. Planning for a departure in 210 minutes is just not as intuitive as in 3:30 hours.

It would be great to add an option, which allows to select between minutes only, or hours and minutes.

**Comment by cifland** [comment]
That's a great idea, I could use that feature as well!
I'll try to implement it :)

**Comment by cgtobi** [comment]
Implemented in https://github.com/custom-cards/rmv-card/pull/10
Thanks @cifland
